// apps/react-app/src/modules/todo/components/loading-sketch.tsx
import type { ETodoListType } from '@todo/controllers';
import type { FC } from 'react';

import { ServiceLocator } from '@todo/container';
import { areArraysEqual, IDataService } from '@todo/controllers';
import { memo, useMemo, useRef } from 'react';
import ContentLoader from 'react-content-loader';
import { of } from 'rxjs';
import { delay, distinctUntilChanged, map, pairwise, startWith, switchMap } from 'rxjs/operators';

import { useObservableState } from '@/hooks';
import { getElementResize$ } from '@/lib/utils';

export interface ILoadingSketcProps {
  type: ETodoListType;
}

const defaultRowWidth = [364, 300, 332] as [number, number, number];

const dataService = ServiceLocator.default.get(IDataService);

const LoadingSketchCore: FC<ILoadingSketcProps> = ({ type }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  const rowWidth = useObservableState(
    useMemo(
      () =>
        dataService.ends$.pipe(
          map((ends) => ends[type]),
          distinctUntilChanged(),
          switchMap((isEnd) =>
            isEnd || !containerRef.current
              ? of(defaultRowWidth)
              : getElementResize$(containerRef.current, (v) => [v.clientWidth, v.clientHeight] as const).pipe(
                  distinctUntilChanged((prev, curr) => prev[0] === curr[0] && prev[1] === curr[1]),
                  startWith([0, 0] as const),
                  pairwise(),
                  switchMap((val) => {
                    const next$ = of(val[1][0]);
                    return val[0][1] !== val[1][1] ? next$ : next$.pipe(delay(2000));
                  }),
                  distinctUntilChanged(),
                  map((rowWidth) => {
                    const contentWidth = rowWidth - 16 - (16 + 8) * 2;
                    const dateIconLeft = rowWidth - 16 - 16;

                    return [rowWidth, contentWidth, dateIconLeft];
                  }),
                ),
          ),
        ),
      [type],
    ),
    defaultRowWidth,
    areArraysEqual,
  );

  return (
    <div ref={containerRef}>
      <ContentLoader
        speed={0.5}
        width={rowWidth[0]}
        height={40}
        viewBox={`0 0 ${String(rowWidth[0])} 40`}
        backgroundColor="#d9d9d9"
        foregroundColor="#ededed"
      >
        <rect x="0" y="12" rx="1" ry="1" width="16" height="16" />
        <rect x="24" y="10" rx="4" ry="4" width={rowWidth[1]} height="20" />
        <rect x={rowWidth[2]} y="12" rx="1" ry="1" width="16" height="16" />
      </ContentLoader>
    </div>
  );
};
export const LoadingSketch = memo(LoadingSketchCore);

// apps/vue-app/src/modules/todo/components/loading-sketch.tsx
import type { ETodoListType } from '@todo/controllers';

import { ServiceLocator } from '@todo/container';
import { areArraysEqual, IDataService } from '@todo/controllers';
import { delay, distinctUntilChanged, map, of, pairwise, startWith, switchMap } from 'rxjs';
import { defineComponent, type PropType, ref } from 'vue';
import { ContentLoader } from 'vue-content-loader';

import { useObservableShallowRef } from '@/hooks';
import { getElementResize$ } from '@/lib/utils';

const defaultRowWidth = [430, 366, 398] as [number, number, number];

const dataService = ServiceLocator.default.get(IDataService);

export const LoadingSketch = defineComponent({
  name: 'LoadingSketchCore',
  props: {
    type: { type: String as PropType<ETodoListType>, required: true },
  },
  setup(props) {
    const containerRef = ref<HTMLDivElement>();

    const rowWidthRef = useObservableShallowRef(
      dataService.ends$.pipe(
        map((ends) => ends[props.type]),
        distinctUntilChanged(),
        switchMap((isEnd) =>
          isEnd || !containerRef.value
            ? of(defaultRowWidth)
            : getElementResize$(containerRef.value, (v) => [v.clientWidth, v.clientHeight] as const).pipe(
                distinctUntilChanged((prev, curr) => prev[0] === curr[0] && prev[1] === curr[1]),
                startWith([0, 0] as const),
                pairwise(),
                switchMap((val) => {
                  const next$ = of(val[1][0]);
                  return val[0][1] !== val[1][1] ? next$ : next$.pipe(delay(2000));
                }),
                distinctUntilChanged(),
                map((rowWidth) => {
                  const contentWidth = rowWidth - 16 - (16 + 8) * 2;
                  const dateIconLeft = rowWidth - 16 - 16;

                  return [rowWidth, contentWidth, dateIconLeft];
                }),
              ),
        ),
        distinctUntilChanged(areArraysEqual),
      ),
      defaultRowWidth,
    );

    return () => (
      <div ref={containerRef}>
        <ContentLoader
          speed={0.5}
          width={rowWidthRef.value[0]}
          height={40}
          viewBox={`0 0 ${String(rowWidthRef.value[0])} 40`}
          primaryColor="#d9d9d9"
          secondaryColor="#ededed"
        >
          <rect x="0" y="12" rx="1" ry="1" width="16" height="16" />
          <rect x="24" y="10" rx="4" ry="4" width={rowWidthRef.value[1]} height="20" />
          <rect x={rowWidthRef.value[2]} y="12" rx="1" ry="1" width="16" height="16" />
        </ContentLoader>
      </div>
    );
  },
});
