// apps/nextjs-app/modules/todo/create-new.tsx
'use client';

import type { FC } from 'react';

import { zodResolver } from '@hookform/resolvers/zod';
import { ServiceLocator } from '@todo/container';
import { Loader2 } from 'lucide-react';
import { memo, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { asyncScheduler, observeOn, tap } from 'rxjs';
import { toast } from 'sonner';
import { z } from 'zod';

import { language$ } from '@/components/monitor';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { useLoading } from '@/hooks';
import { useIntl } from '@/i18n';
import { IDBDataService } from '@/services/resources';

import { DatePicker } from './components/date-picker';

const CreateNewTaskCore: FC = () => {
  const { t } = useIntl('todo.create-new');

  const formSchema = z.object({
    title: z.string().min(2, { message: t('validation-rules.title-length') }),
    date: z.date().nullable(),
  });

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: { title: '', date: null },
  });

  const { clearErrors } = form;
  useEffect(() => {
    const subscription = language$.subscribe(() => {
      clearErrors('title');
    });
    return () => {
      subscription.unsubscribe();
    };
  }, [clearErrors]);

  const { handleSubmit, reset, setFocus } = form;
  const [loading, handleEvent] = useLoading((data: z.infer<typeof formSchema>) => {
    return ServiceLocator.default
      .get(IDBDataService)
      .add({
        title: data.title,
        overdueAt: data.date?.valueOf(),
      })
      .pipe(
        tap(() => {
          toast(t('create-success'), { duration: 1_000 });
          reset();
        }),
        observeOn(asyncScheduler),
        tap(() => {
          setFocus('title');
        }),
      );
  });

  return (
    <Form {...form}>
      <form
        className="h-[4.25rem] relative flex flex-row space-x-2"
        onSubmit={(e) => void handleSubmit(handleEvent)(e)}
      >
        <FormField
          control={form.control}
          name="title"
          render={({ field }) => (
            <FormItem className="flex-auto">
              <FormControl>
                <Input placeholder={t('input-placeholder')} {...field} disabled={loading} />
              </FormControl>
              <FormMessage className="absolute left-0 bottom-0" />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="date"
          render={({ field }) => (
            <FormItem className="flex-initial">
              <FormControl>
                <DatePicker value={field.value} onChange={field.onChange} disabled={loading} />
              </FormControl>
            </FormItem>
          )}
        />
        <Button type="submit" className="flex-initial" disabled={loading}>
          {loading && <Loader2 className="animate-spin mr-2" width={18} height={18} />}
          {t('submit-form')}
        </Button>
      </form>
    </Form>
  );
};
export const CreateNewTask = memo(CreateNewTaskCore);

// apps/nuxtjs-app/app/sections/todo/create-new.tsx
import type { IFieldRendererEventArgs } from './types';
import type { Observable } from 'rxjs';

import { ServiceLocator } from '@todo/container';
import { toTypedSchema } from '@vee-validate/zod';
import { Loader2 } from 'lucide-vue-next';
import { filter, of, switchMap, take, tap } from 'rxjs';
import { useForm } from 'vee-validate';
import { defineComponent } from 'vue';
import { toast } from 'vue-sonner';
import { z } from 'zod';

import { useIntl } from '@/i18n';
import { IDBDataService } from '~/services/resources';
import { Button } from '~/ui/button';
import { FormControl, FormField, FormItem, FormMessage } from '~/ui/form';
import { Input } from '~/ui/input';

import { DatePicker } from './components/date-picker';

export const CreateNewTask = defineComponent({
  name: 'CreateNewTask',
  setup() {
    const { t, n } = useIntl('todo.create-new');
    const dataService = ServiceLocator.default.get(IDBDataService);

    const formSchema = z.object({
      title: z.string().min(2, { message: n('validation-rules.title-length') }),
      date: z.date().nullable(),
    });

    const form = useForm({
      validationSchema: toTypedSchema(formSchema),
      initialValues: { title: '', date: null },
    });

    const [handleBlur] = useAsyncEvent<FocusEvent>((e) =>
      of(e.currentTarget as HTMLInputElement | null).pipe(
        filter((v) => !!v && !v.value),
        tap(() => {
          form.setFieldError('title', []);
        }),
      ),
    );

    const refresh$ = useUpdate();
    const [inputRef, input$] = useRef<{ el$: Observable<HTMLInputElement> }>();
    const [handleEvent, loadingRef] = useAsyncEvent((data: z.infer<typeof formSchema>) =>
      dataService.add({ title: data.title, overdueAt: data.date?.valueOf() }).pipe(
        tap(() => {
          toast(t('create-success'), { duration: 1_000 });
          form.resetForm();

          refresh$
            .pipe(
              switchMap(() => input$),
              filter((v) => !!v),
              switchMap((v) => v.el$),
              take(1),
            )
            .subscribe((el) => {
              el.focus();
            });
        }),
      ),
    );

    const handleSubmit = (e: Event) => void form.handleSubmit(handleEvent)(e);
    return () => (
      <form class="h-[4.25rem] relative flex flex-row space-x-2" onSubmit={handleSubmit}>
        <FormField name="title">
          {({ field }: IFieldRendererEventArgs<string | undefined, string | number | undefined>) => (
            <FormItem class="flex-auto space-y-0">
              <FormControl>
                <Input
                  ref={inputRef}
                  modelValue={field.value}
                  disabled={loadingRef.value}
                  placeholder={t('input-placeholder')}
                  onBlur={handleBlur}
                  onUpdate:modelValue={field['onUpdate:modelValue']}
                />
              </FormControl>
              <FormMessage class="absolute left-0 bottom-2 text-xs" />
            </FormItem>
          )}
        </FormField>
        <FormField name="date">
          {({ field }: IFieldRendererEventArgs<Date | null>) => (
            <FormItem class="flex-none">
              <FormControl>
                <DatePicker {...field} disabled={loadingRef.value} />
              </FormControl>
            </FormItem>
          )}
        </FormField>
        <Button size="lg" type="submit" class="flex-initial px-4" disabled={loadingRef.value || !form.meta.value.valid}>
          {loadingRef.value && <Loader2 class="animate-spin" width={18} height={18} />}
          {t('submit-form')}
        </Button>
      </form>
    );
  },
});
