// apps/vue-app/src/modules/todo/item.tsx
import { ServiceLocator } from '@todo/container';
import { ETodoStatus, IDataService } from '@todo/controllers';
import { Loader2 } from 'lucide-vue-next';
import { concatMap, distinctUntilChanged, filter, map, shareReplay, take } from 'rxjs';
import { defineComponent } from 'vue';

import { Checkbox } from '@/components/ui/checkbox';
import { useLoading, useObservableShallowRef } from '@/hooks';

import { AutoTooltip } from './components/auto-tooltip';
// import { RowContextMenu } from './components/row-context-menu';
// import { RowDatePicker } from './components/row-data-picker';
// import { TodoItemEditor } from './editor';

const dataService = ServiceLocator.default.get(IDataService);

export const TodoItem = defineComponent({
  name: 'TodoItem',
  props: {
    id: { type: String, required: true },
    dateFormatString: { type: String, required: true },
  },
  setup(props) {
    const item$ = dataService.dataMapper$.pipe(
      map((mapper) => mapper[props.id]),
      distinctUntilChanged(),
      filter((v) => !!v),
      shareReplay(1),
    );
    const itemRef = useObservableShallowRef(item$, dataService.dataMapper[props.id]);

    const [loadingRef, handleChangeChecked] = useLoading((e: boolean) =>
      item$.pipe(
        take(1),
        concatMap((item) => dataService.update({ ...item, status: e ? ETodoStatus.DONE : ETodoStatus.PENDING })),
      ),
    );

    const handleOpenEditor = () => {
      console.log('Open Editor');
    };

    // const overdueAt = computed(() => (item.overdueAt ? new Date(item.overdueAt) : undefined), [item.overdueAt]);
    return () => (
      <div class="flex items-center space-x-2 pr-4">
        {loadingRef.value ? (
          <Loader2 class="animate-spin" width={16} height={16} />
        ) : (
          <Checkbox checked={itemRef.value.status === ETodoStatus.DONE} onUpdate:checked={handleChangeChecked} />
        )}
        <AutoTooltip
          title={itemRef.value.title}
          description={itemRef.value.description ? itemRef.value.description : itemRef.value.title}
          className="text-sm font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer truncate"
          onClick={handleOpenEditor}
        />
        <div class="flex-auto" />
      </div>
    );
  },
});

// apps/react-app/src/modules/todo/item.tsx
import type { CheckedState } from '@radix-ui/react-checkbox';
import type { CSSProperties, FC } from 'react';

import { ServiceLocator } from '@todo/container';
import { ETodoStatus, IDataService } from '@todo/controllers';
import { Loader2 } from 'lucide-react';
import { memo, useCallback, useMemo, useState } from 'react';
import { concatMap, distinctUntilChanged, filter, map, shareReplay, take } from 'rxjs/operators';

import { Checkbox } from '@/components/ui/checkbox';
import { useLoading, useObservableState } from '@/hooks';

import { AutoTooltip } from './components/auto-tooltip';
import { RowContextMenu } from './components/row-context-menu';
import { RowDatePicker } from './components/row-data-picker';
import { TodoItemEditor } from './editor';

export interface ITodoItemProps {
  id: string;
  style: CSSProperties;
  dateFormatString: string;
}

const dataService = ServiceLocator.default.get(IDataService);

const TodoItemCore: FC<ITodoItemProps> = ({ id, dateFormatString, style }) => {
  const item$ = useMemo(
    () =>
      dataService.dataMapper$.pipe(
        map((mapper) => mapper[id]),
        distinctUntilChanged(),
        filter((v) => !!v),
        shareReplay(1),
      ),
    [id],
  );
  const item = useObservableState(item$, dataService.dataMapper[id]);

  const [loading, handleChangeChecked] = useLoading((e: CheckedState) =>
    item$.pipe(
      take(1),
      concatMap((item) => dataService.update({ ...item, status: e === true ? ETodoStatus.DONE : ETodoStatus.PENDING })),
    ),
  );

  const [open, setOpen] = useState(false);
  const handleOpenEditor = useCallback(() => {
    setOpen(true);
  }, []);

  const overdueAt = useMemo(() => (item.overdueAt ? new Date(item.overdueAt) : undefined), [item.overdueAt]);
  return (
    <div className="flex items-center space-x-2 pr-4" style={style}>
      {loading ? (
        <Loader2 className="animate-spin" width={16} height={16} />
      ) : (
        <Checkbox checked={item.status === ETodoStatus.DONE} onCheckedChange={handleChangeChecked} />
      )}
      <RowContextMenu id={id}>
        <AutoTooltip
          title={item.title}
          description={item.description ? item.description : item.title}
          className="text-sm font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer truncate"
          onClick={handleOpenEditor}
        />
      </RowContextMenu>
      <div className="flex-auto" />
      <RowDatePicker className="flex-initial" id={id} value={overdueAt} formatString={dateFormatString} />
      <TodoItemEditor id={id} open={open} onOpenChange={setOpen} />
    </div>
  );
};
export const TodoItem = memo(
  TodoItemCore,
  (prev, next) => prev.id === next.id && prev.dateFormatString === next.dateFormatString,
);
