// apps/vue-app/src/modules/todo/components/auto-tooltip.tsx
import { combineLatest, filter, map, of, switchMap } from 'rxjs';
import { computed, defineComponent } from 'vue';

import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { useObservableRef, useObservableWatch, useRef } from '@/hooks';
import { listenResize$ } from '@/lib/listen-resize';

export const AutoTooltip = defineComponent({
  name: 'AutoTooltip',
  props: {
    title: { type: String, required: true },
    description: { type: String, required: true },
    className: { type: String, default: '' },
  },
  setup(props) {
    const [containerRef, container$] = useRef<HTMLDivElement>();
    const [realElementRef, realElement$] = useRef<HTMLDivElement>();

    const props$ = useObservableWatch(() => props, { deep: true });
    const disabledRef = useObservableRef(
      props$.pipe(
        switchMap((p) => {
          if (p.title !== p.description) {
            return of(false);
          } else {
            return combineLatest([
              container$.pipe(filter((v) => !!v)),
              realElement$.pipe(
                filter((v) => !!v),
                switchMap((el) =>
                  listenResize$(el).pipe(
                    filter((entries) => !!entries.length),
                    map((entries) => entries[0]),
                  ),
                ),
              ),
            ]).pipe(
              map(
                ([containerElement, entry]) =>
                  entry.contentRect.height <= containerElement.getBoundingClientRect().height,
              ),
            );
          }
        }),
      ),
      true,
    );

    const containerClassNameRef = computed(() => ['relative overflow-hidden', props.className].join(' '));
    return () => (
      <TooltipProvider disabled={disabledRef.value}>
        <Tooltip>
          <TooltipTrigger>
            <div ref={containerRef} class={disabledRef.value ? containerClassNameRef.value : ''}>
              <div class="truncate">{props.title}</div>
              <div ref={realElementRef} class="absolute invisible top-0 left-0 text-wrap">
                {props.title}
              </div>
            </div>
          </TooltipTrigger>
          <TooltipContent>
            <div class="max-w-lg whitespace-break-spaces">{props.description}</div>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  },
});

// src/modules/todo/components/auto-tooltip.tsx
import type { FC } from 'react';

import { useEffect, useRef, useState } from 'react';

import { Tooltip, TooltipContent, TooltipPortal, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';

export interface IAutoTooltipWithDescriptionProps {
  title: string;
  description: string;
  className?: string;
  onClick: () => void;
}

export const AutoTooltip: FC<IAutoTooltipWithDescriptionProps> = (props) => {
  const { className, onClick, description, title } = props;

  const [disabled, setDisabled] = useState(true);

  const containerRef = useRef<HTMLDivElement>(null);
  const realElementRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const targetElement = realElementRef.current;
    if (!targetElement) return;

    if (title !== description) {
      setDisabled(false);
    } else {
      const observer = new ResizeObserver((entries) => {
        if (!entries.length) return;

        const entry = entries[0];
        const containerElement = containerRef.current;
        setDisabled(
          containerElement ? entry.contentRect.height <= containerElement.getBoundingClientRect().height : false,
        );
      });
      observer.observe(targetElement);

      return () => {
        observer.unobserve(targetElement);
        observer.disconnect();
      };
    }
  }, [title, description, disabled]); // fire effect after changed disabled variable

  const containerClassName = ['relative overflow-hidden', className ?? ''].join(' ');
  const trigger = (
    <div ref={containerRef} className={disabled ? containerClassName : ''} onClick={onClick}>
      <div className="truncate">{title}</div>
      <div ref={realElementRef} className="absolute invisible top-0 left-0 text-wrap">
        {title}
      </div>
    </div>
  );

  if (disabled) return trigger;
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger className={containerClassName}>{trigger}</TooltipTrigger>
        <TooltipPortal>
          <TooltipContent>
            <div className="max-w-lg">{description}</div>
          </TooltipContent>
        </TooltipPortal>
      </Tooltip>
    </TooltipProvider>
  );
};
