// apps/solid-app/src/modules/todo/list.tsx
import { ServiceLocator } from '@todo/container';
import { areArraysEqual, ETodoListType, IDataService } from '@todo/controllers';
import dayjs from 'dayjs';
import {
  auditTime,
  combineLatest,
  distinct,
  distinctUntilChanged,
  EMPTY,
  exhaustMap,
  filter,
  from,
  map,
  merge,
  of,
  shareReplay,
  skip,
  switchMap,
  take,
  tap,
  toArray,
} from 'rxjs';

import { VirtualizedList } from '@/components/virtualized';
import { EUpdateType, useObservableEffect, useObservableRef, useObservableSignal, useUpdate } from '@/hooks';
import { useIntl } from '@/i18n';
import { windowResize$ } from '@/libs/listen-resize';

import { LoadingSketch } from './components/loading-sketch';
import { TodoItem } from './item';

const dataService = ServiceLocator.default.get(IDataService);

const DEFAULT_LIST_HEIGHT = 240;

const loadingItems = new Array<string>(10).fill('-1-');

export interface TodoListProps {
  type: ETodoListType;
}

export const TodoList = (props: TodoListProps) => {
  const ids$ = dataService.ids$.pipe(
    map((mapper) => mapper[props.type]),
    distinctUntilChanged(areArraysEqual),
    shareReplay(1),
  );
  const ids = useObservableSignal(
    ids$.pipe(
      switchMap((list) =>
        dataService.ends$.pipe(
          map((mapper) => mapper[props.type]),
          map((isEnd) => (isEnd ? list : list.concat(loadingItems))),
        ),
      ),
    ),
    loadingItems,
  );

  const { t } = useIntl('todo.list');
  const dateFormatString = useObservableSignal(
    ids$.pipe(
      switchMap((ids) =>
        dataService.dataMapper$.pipe(
          map((mapper) =>
            ids
              .map((id) => mapper[id].overdueAt)
              .filter((v) => !!v)
              .map((date) => dayjs(date).get('year')),
          ),
        ),
      ),
      filter((v) => !!v.length),
      switchMap((list) =>
        from(list).pipe(
          distinct(),
          toArray(),
          map((innerList) => {
            const thisYear = dayjs().get('year');
            return innerList.filter((v) => v !== thisYear).length > 0 ? t('full-date') : t('short-date');
          }),
        ),
      ),
    ),
    t('short-date'),
  );

  const refresh$ = useUpdate(EUpdateType.ALL, ids);
  const [setScroller, distance$] = useObservableRef<number>();
  useObservableEffect(
    combineLatest([
      distance$.pipe(filter((v) => typeof v !== 'undefined')),
      dataService.ends$.pipe(map((mapper) => mapper[props.type])),
    ]).pipe(
      filter(([distance, end]) => !end && distance < 400),
      exhaustMap(([distance]) =>
        dataService.ends[props.type]
          ? EMPTY
          : dataService.loadMore(props.type).pipe(
              tap(() =>
                refresh$
                  .pipe(
                    filter((v) => v === EUpdateType.UPDATED),
                    take(1),
                  )
                  .subscribe(() => {
                    setScroller(distance);
                  }),
              ),
            ),
      ),
    ),
  );

  const [containerRef, container$] = useObservableRef<HTMLDivElement>();
  const listHeight = useObservableSignal(
    merge(
      refresh$.pipe(
        filter((v) => v === EUpdateType.MOUNTED),
        switchMap(() => windowResize$),
        take(1),
      ),
      windowResize$.pipe(skip(1), auditTime(60)),
    ).pipe(
      switchMap((v) => {
        if (v[0] >= 768) return of(DEFAULT_LIST_HEIGHT);

        return container$.pipe(map((el) => v[1] - (el?.getBoundingClientRect().top ?? 218) - 6));
      }),
    ),
    DEFAULT_LIST_HEIGHT,
  );

  const renderItem = (index: number) => {
    const id = ids()[index];
    if (id == '-1-') {
      return <LoadingSketch type={ETodoListType.PENDING} />;
    } else {
      return <TodoItem id={id} dateFormatString={dateFormatString()} />;
    }
  };

  return (
    <div ref={containerRef}>
      <VirtualizedList
        height={listHeight()}
        itemHeight={40}
        totalCount={ids().length}
        buffer={1}
        onScroll={setScroller}
      >
        {renderItem}
      </VirtualizedList>
    </div>
  );
};

// apps/vue-app/src/modules/todo/list.tsx
import type { ETodoListType } from '@todo/controllers';
import type { CSSProperties, PropType } from 'vue';

import { ServiceLocator } from '@todo/container';
import { areArraysEqual, IDataService, TODO_LIST_PAGE_SIZE } from '@todo/controllers';
import dayjs from 'dayjs';
import {
  auditTime,
  distinct,
  distinctUntilChanged,
  EMPTY,
  exhaustMap,
  filter,
  from,
  map,
  merge,
  shareReplay,
  skip,
  switchMap,
  take,
  tap,
  toArray,
} from 'rxjs';
import { defineComponent } from 'vue';
// @ts-expect-error 7016 -- this package doesn't have the type definition.
import { DynamicScroller, DynamicScrollerItem } from 'vue-virtual-scroller';

import { EUpdateType, useObservableEffect, useObservableShallowRef, useScrollListener, useUpdate } from '@/hooks';
import { useIntl } from '@/i18n';
import { windowResize$ } from '@/lib/utils';

import { LoadingSketch } from './components/loading-sketch';
import { TodoItem } from './item';

import 'vue-virtual-scroller/dist/vue-virtual-scroller.css';

export interface ITodoIdentity {
  id: string;
  type: 'item' | 'polyfill';
}

export interface ITodoItemRenderer {
  item: ITodoIdentity;
  index: number;
  active: boolean;
}

const dataService = ServiceLocator.default.get(IDataService);

const defaultListStyle: CSSProperties = { height: '240px' };

const loadingItems: ITodoIdentity[] = [{ id: `###0`, type: 'polyfill' }];

export const TodoList = defineComponent({
  name: 'TodoList',
  props: {
    type: {
      type: String as PropType<ETodoListType>,
      required: true,
    },
  },
  setup(props) {
    const ids$ = dataService.ids$.pipe(
      map((mapper) => mapper[props.type]),
      distinctUntilChanged(areArraysEqual),
      shareReplay(1),
    );
    const idsRef = useObservableShallowRef(
      ids$.pipe(
        map((ids) => ids.map((id) => ({ id, type: 'item' }) as ITodoIdentity)),
        switchMap((list) =>
          dataService.ends$.pipe(
            map((mapper) => mapper[props.type]),
            map((isEnd) => (isEnd ? list : list.concat(loadingItems))),
          ),
        ),
      ),
      loadingItems,
    );

    const { t } = useIntl('todo.list');
    const dateFormatString = useObservableShallowRef(
      ids$.pipe(
        switchMap((ids) =>
          dataService.dataMapper$.pipe(
            map((mapper) =>
              ids
                .map((id) => mapper[id].overdueAt)
                .filter((v) => !!v)
                .map((date) => dayjs(date).get('year')),
            ),
          ),
        ),
        filter((v) => !!v.length),
        switchMap((list) =>
          from(list).pipe(
            distinct(),
            toArray(),
            map((innerList) => {
              const thisYear = dayjs().get('year');
              return innerList.filter((v) => v !== thisYear).length > 0 ? t('full-date') : t('short-date');
            }),
          ),
        ),
      ),
      t('short-date'),
    );

    const refresh$ = useUpdate(EUpdateType.ALL);
    const [refs, entry$, handleCheck] = useScrollListener();
    useObservableEffect(
      entry$
        .pipe(
          map((v) => v.intersectionRatio),
          filter((v) => v > 0),
          exhaustMap(() =>
            dataService.ends[props.type]
              ? EMPTY
              : dataService.loadMore(props.type).pipe(
                  tap(() =>
                    refresh$
                      .pipe(
                        filter((v) => v === EUpdateType.UPDATED),
                        take(1),
                      )
                      .subscribe(handleCheck),
                  ),
                ),
          ),
        )
        .subscribe(),
    );

    const listStyle = useObservableShallowRef(
      merge(
        refresh$.pipe(
          filter((v) => v === EUpdateType.MOUNTED),
          switchMap(() => windowResize$),
          take(1),
        ),
        windowResize$.pipe(skip(1), auditTime(60)),
      ).pipe(
        map((v) => {
          if (v.width >= 768) return defaultListStyle;

          const height = v.height - (refs.container.value?.getBoundingClientRect().top ?? 218) - 6;
          return { height: `${height.toString()}px` } as CSSProperties;
        }),
      ),
      defaultListStyle,
    );

    return () => (
      <div ref={refs.container}>
        <DynamicScroller minItemSize={40} buffer={10} items={idsRef.value} style={listStyle.value}>
          {({ item, active }: ITodoItemRenderer) => (
            <DynamicScrollerItem key={item.id} item={item} active={active} sizeDependencies={[item.type]}>
              {item.id === '###0' ? (
                <div ref={refs.target}>
                  {new Array<number>(TODO_LIST_PAGE_SIZE).fill(0).map((_, index) => (
                    <LoadingSketch key={index} type={props.type} />
                  ))}
                </div>
              ) : (
                <TodoItem id={item.id} dateFormatString={dateFormatString.value} />
              )}
            </DynamicScrollerItem>
          )}
        </DynamicScroller>
      </div>
    );
  },
});
