// apps/solid-app/src/index.tsx
/* @refresh reload */
import { lazy, Suspense } from 'solid-js';
import { render } from 'solid-js/web';

import { i18n } from './i18n';

import './index.css';

const root = document.getElementById('root');
if (root) {
  const App = lazy(() => Promise.all([import('./App'), i18n.ready]).then(([App]) => App));
  render(
    () => (
      <Suspense fallback={<div>Loading</div>}>
        <App />
      </Suspense>
    ),
    root,
  );
}

// src/main.tsx
import 'reflect-metadata';

import { lazy, StrictMode, Suspense } from 'react';
import { createRoot } from 'react-dom/client';

import { intl } from './i18n';

import './index.css';

// eslint-disable-next-line react-refresh/only-export-components -- this is the entrance
const App = lazy(() => Promise.all([import('./App'), intl]).then(([App]) => App));

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <Suspense fallback={<div>Loading</div>}>
      <App />
    </Suspense>
  </StrictMode>,
);
